name: "Release dev container features"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v2
      
      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          oci-registry: "devwasm.azurecr.io"
          base-path-to-features: "./src"
          disable-repo-tagging: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVCONTAINERS_OCI_AUTH: ${{ secrets.DEVCONTAINERS_OCI_AUTH }}